# coding: utf-8

"""
    Library Reservation System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.books_api import BooksApi


class TestBooksApi(unittest.TestCase):
    """BooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_book_books_post(self) -> None:
        """Test case for create_book_books_post

        Create Book
        """
        pass

    def test_get_book_books_book_id_get(self) -> None:
        """Test case for get_book_books_book_id_get

        Get Book
        """
        pass

    def test_get_books_books_get(self) -> None:
        """Test case for get_books_books_get

        Get Books
        """
        pass

    def test_reserve_book_books_book_id_reserve_post(self) -> None:
        """Test case for reserve_book_books_book_id_reserve_post

        Reserve Book
        """
        pass


if __name__ == '__main__':
    unittest.main()
