# coding: utf-8

"""
    Library Reservation System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.reservations_api import ReservationsApi


class TestReservationsApi(unittest.TestCase):
    """ReservationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReservationsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_reservation_reservations_reservation_id_delete(self) -> None:
        """Test case for cancel_reservation_reservations_reservation_id_delete

        Cancel Reservation
        """
        pass


if __name__ == '__main__':
    unittest.main()
