# coding: utf-8

"""
    Library Reservation System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book_response import BookResponse

class TestBookResponse(unittest.TestCase):
    """BookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookResponse:
        """Test BookResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookResponse`
        """
        model = BookResponse()
        if include_optional:
            return BookResponse(
                id = 56,
                title = '',
                author = '',
                total_copies = 56,
                available_copies = 56
            )
        else:
            return BookResponse(
                id = 56,
                title = '',
                author = '',
                total_copies = 56,
                available_copies = 56,
        )
        """

    def testBookResponse(self):
        """Test BookResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
