# coding: utf-8

# flake8: noqa

"""
    Library Reservation System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BooksApi",
    "ReservationsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BookCreate",
    "BookResponse",
    "HTTPValidationError",
    "LocationInner",
    "ReservationCreate",
    "ReservationResponse",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.books_api import BooksApi as BooksApi
from openapi_client.api.reservations_api import ReservationsApi as ReservationsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.book_create import BookCreate as BookCreate
from openapi_client.models.book_response import BookResponse as BookResponse
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.reservation_create import ReservationCreate as ReservationCreate
from openapi_client.models.reservation_response import ReservationResponse as ReservationResponse
from openapi_client.models.validation_error import ValidationError as ValidationError

